Data card brazil
BigDataWUR/AgML-crop-yield-forecasting pull request #110
Opened 2024-03-26 16:11 UTC by Raed-Hamed

2024-03-26 16:57 UTC, krsnapaudel requested changes
The data card looks good. In the preprocessing script, the `adm_id` is all numbers. It would be good to have country code in it.

2024-04-09 10:36 UTC, Raed-Hamed commented
Adjusted to include country code as prefix to adm_id number

2024-04-09 11:06 UTC, mnqoliveira commented
Hi! I had mentioned to Max, but maybe he had not had the opportunity to change, but I found the licensing in other government website:

https://dados.gov.br/dados/conjuntos-dados/pa-producao-agricola-municipal
Looks like it's public domain.

2024-04-12 14:32 UTC, krsnapaudel approved these changes

2024-04-14 10:54 UTC, merged