add AUS datacards
BigDataWUR/AgML-crop-yield-forecasting pull request #125
Opened 2024-04-12 10:44 UTC by JRichetti

Add shapefiles and data cards for Australia

2024-04-19 12:36 UTC, ellaampy commented on data_preparation/crop_statistics_AUS/README.md
> +**Variables** [unit]: t / ha
please here the variables available in the database and their unit e.g. yield [t/ha], production [t], area sown [ha]. The R script shows the database also contains production and area sown.

2024-04-19 12:39 UTC, ellaampy commented on data_preparation/crop_statistics_AUS/From abares to wheat df for AgML.R
> +  theme_bw()
@JRichetti could you please produce the final table according to the prescribed data format. kindly check an example table for India [here](https://github.com/BigDataWUR/AgML-crop-yield-forecasting/blob/main/data_preparation/crop_statistics_IN/data_preparation.ipynb) (at the end of the script)

2024-04-19 12:40 UTC, ellaampy requested changes
@JRichetti please address the comments on crop statistics readme and data preparation script

2024-04-23 06:20 UTC, krsnapaudel requested changes
There are some lines copied from the data card template and not filled in correctly.
Examples: Provenance and References.

Similarly, variables are not included.

For shapefiles data card. Please check a similar example from EU or US to include expected overview.

2024-04-23 08:58 UTC, JRichetti commented
I'm not super savy with git, can you check if what I pushed is as expected now?

2024-04-24 08:15 UTC, krsnapaudel commented
@JRichetti : ideally we would want the official shapefiles that include all admin boundaries up to the units with statistics.

2024-04-24 08:16 UTC, krsnapaudel commented on data_preparation/shapefile_AU/README.md
> +# Australian Regions (ABARES)
The directory name should be `shapefiles_AU`.

2024-04-24 08:17 UTC, krsnapaudel commented on data_preparation/shapefile_AU/README.md
> +Boult, C & Jackson, T 2019, ‘Disaggregating farm performance statistics by size, 2017–18’, in Agricultural Commodities: March quarter 2019, Australian Bureau of Agricultural and Resource Economics an
This seems copied from previous README. Please update.

2024-05-27 08:42 UTC, JRichetti commented
I've updated the script and the readme files. I also uploaded the updated data and shapes with matching adm_id to the Google drive. Hope it is ok now.

2024-05-27 11:03 UTC, krsnapaudel approved these changes

2024-05-27 11:03 UTC, krsnapaudel commented
Thanks @JRichetti. I will rename your script. Otherwise it's good.

2024-05-27 11:04 UTC, krsnapaudel commented
@ellaampy : merging is blocked because of your review. Please see updates. Thanks.

2024-05-27 11:07 UTC, ellaampy approved these changes

2024-05-27 11:07 UTC, merged