Update README.md
BigDataWUR/AgML-crop-yield-forecasting pull request #205
Opened 2024-05-29 08:44 UTC by Raed-Hamed

Updated shapefile Card for Brazil. Previous one didn't reflect admin id levels, and therfore didnt allow for straighforward merging.

2024-05-29 08:49 UTC, krsnapaudel requested changes

2024-05-29 10:52 UTC, Raed-Hamed commented on data_preparation/shapefiles_BR/README.md
> +Select filename *bra_admbnda_adm2_ibge_2020.shp* for admin 2 level data.
provenance and license are still there. Just more compact in the data overview section. Added a bit more information all around to further detail some aspects (see commit message)

2024-05-29 16:32 UTC, krsnapaudel commented on data_preparation/shapefiles_BR/README.md
> +Select filename *bra_admbnda_adm2_ibge_2020.shp* for admin 2 level data.
Those sections must be separate. Based on the template.

2024-05-30 09:52 UTC, krsnapaudel approved these changes

2024-05-30 09:52 UTC, merged