#56 Data Preparation Functionality for TIFF
BigDataWUR/AgML-crop-yield-forecasting pull request #84
Opened 2024-03-01 14:13 UTC by AbdelrahmanAmr3

Add data preparation scripts for all predictors in TIFF format.

2024-03-11 10:15 UTC, krsnapaudel requested changes
Some documentation would help to understand your overall logic.

2024-03-12 07:58 UTC, AbdelrahmanAmr3 commented
> Some documentation would help you understand your overall logic.

Hi Dilli, I have added complete documentation for the overall logic of the workflow in main.py.  I hope it will be crystal clear now.  As this function workflow is the same as my EarthStat library, this is the diagram for the workflow.

![EarthStat](https://github.com/BigDataWUR/AgML-crop-yield-forecasting/assets/63993013/a09ae199-14c7-4396-bb23-22dc391e7d5d)

2024-03-15 00:16 UTC, ellaampy reviewed
@AbdelrahmanAmr3 thanks for a nice logic to harmonize the different datasets. please see the in-line comments

2024-03-15 00:16 UTC, ellaampy commented on util/geoutils.py
> +                        valid_mask = (mask_image != no_data_value)
@AbdelrahmanAmr3 if the nodata value in the crop mask happen to be nan, then (mask_iimage!=no_data_value) will always return true for nans. for such cases, perhaps ~np.isnan(mask_iimage)?

2024-03-15 00:16 UTC, ellaampy commented on util/geoutils.py
> +        rescaled_data = ((crop_mask_data - old_min) /
@AbdelrahmanAmr3 could this fail with nans in the cropmask?

2024-05-31 15:46 UTC, krsnapaudel commented
Covered by #213

2024-05-31 15:46 UTC, closed without merging